### ISSUE TITLE
[Docs] : dbcp2 로 설정되어있는 .yml 수정 필요

### ISSUE THREAD

**Issue by shbaeNhnacademy** [NHN-YesAladin/yesaladin_auth#5]
## 문서 추가/수정 내용
-spring default 인 hikari connection pool 이 아닌 dbcp2로 되어버린 이유 찾기 및  수정

**Comment by alanhakhyeonsong** [comment]
https://github.com/NHN-YesAladin/yesaladin_auth/pull/6

수정 완료했습니다
